version: '2.20.2-desktop.1'

services: 
  app:
    build: .
    command: npm start
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    environment:
      - MONGO_DB_URI=${MONGO_DB_URI}
    networks:
      - mynetwork

  db:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb_data:/data/db
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge